#!/bin/bash

git log | grep Author | sort | uniq -c

git filter-branch -f --env-filter '

    if [ "$GIT_AUTHOR_EMAIL" = "semop@bee32.com" ]; then
        GIT_AUTHOR_NAME=Lenik;
    fi
    if [ "$GIT_AUTHOR_NAME" = "root" ]; then
        GIT_AUTHOR_NAME=Lenik;
    fi
    if [ "$GIT_AUTHOR_NAME" = "lenik" ]; then
        GIT_AUTHOR_NAME=Lenik;
    fi
    if [ "$GIT_AUTHOR_NAME" = "Shecti" ]; then
        GIT_AUTHOR_NAME=Lenik;
    fi
    if [ "$GIT_AUTHOR_EMAIL" = "xjl@99jsj.com" ]; then
        GIT_AUTHOR_NAME=Lenik
    fi
    if [ "$GIT_AUTHOR_NAME" = "Lenik" ]; then
        GIT_AUTHOR_EMAIL=xjl@99jsj.com
    fi

    if [ "$GIT_AUTHOR_EMAIL" = "google.username@gmail.com" ]; then
        GIT_AUTHOR_NAME=jack
    fi
    if [ "$GIT_AUTHOR_NAME" = "jack jin" ]; then
        GIT_AUTHOR_NAME=jack
    fi
    if [ "$GIT_AUTHOR_NAME" = "U-j\jack" ]; then
        GIT_AUTHOR_NAME=jack
    fi
    if [ "$GIT_AUTHOR_EMAIL" = "superjwl@gmail.com" ]; then
        GIT_AUTHOR_NAME=jack
    fi
    if [ "$GIT_AUTHOR_NAME" = "jack" ]; then
        GIT_AUTHOR_EMAIL=superjwl@gmail.com;
    fi

    if [ "$GIT_AUTHOR_NAME" = "zh" ]; then
        GIT_AUTHOR_NAME=ztf
    fi
    if [ "$GIT_AUTHOR_NAME" = "primvera" ]; then
        GIT_AUTHOR_NAME=ztf
    fi
    if [ "$GIT_AUTHOR_NAME" = "ztf" ]; then
        GIT_AUTHOR_EMAIL=ztf@bee32.com
    fi

    GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME";
    GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL";

' HEAD
