#!/bin/bash

POSTSOURCE=/node/type/etc/postinstall
POSTSTATUS=/node/local/etc/postinstalled

mkdir -p $POSTSTATUS

shopt -s nullglob

error_count=0

all=0
if [ "$1" = "-a" ]; then all=1; fi

for src in $POSTSOURCE/*; do

    if [ ! -x "$src" ]; then continue; fi

    stem="${src##*/}"
    dst="$POSTSTATUS/$stem"

    srcver="`date -r $src`"
    dstver=
    if [ -f "$dst.done" ]; then
        dstver="`date -r $dst.done`"
    fi

    if [ $all = 1 -o "$srcver" != "$dstver" ]; then
        printf "Install %-40s" $stem
        if $src 2>&1 >$dst.log; then
            echo "[ OK ]"
            touch -r "$src" "$dst.done"
        else
            echo "[ Failed ]"
            echo "    Please see the log $dst.log"
            ((error_count++))
            rm -f "$dst.done"
        fi
    fi
done

exit $error_count
