#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          seccaw
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SECCAW Application Domain
### END INIT INFO

seccaw "$1"
