#!/bin/bash

pgconfdir=/etc/postgresql

for pgconfvdir in $pgconfdir/*; do
    pgver=${pgconfvdir##*/}
    hba=$pgconfvdir/main/pg_hba.conf
    ifedit --sudo $hba \
        /etc/init.d/postgresql-$pgver restart
done
