#!/bin/bash

trap 'echo signal 1' 1
trap 'echo signal 2' 2
trap 'echo signal 3' 3
trap 'echo signal 4' 4
trap 'echo signal 5' 5
trap 'echo signal 6' 6
trap 'echo signal 7' 7
trap 'echo signal 8' 8
trap 'echo signal 9' 9
trap 'echo signal 10' 10
trap 'echo signal 11' 11
trap 'echo signal 12' 12
trap 'echo signal 13' 13
trap 'echo signal 14' 14
trap 'echo signal 15' 15
trap 'echo signal 16' 16
trap 'echo signal 17' 17
trap 'echo signal 18' 18
trap 'echo signal 19' 19
trap 'echo signal 20' 20

echo "Enter q to exit. "
while true; do
    read LINE
    if [ "$LINE" = "q" ]; then break; fi
done
