#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Change table field names according to tabmap file"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] [MIGDATA-DIR (default .)]"
    echo
    echo "Options: "
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
    echo
    echo "See-Also: "
    echo "    tabmap(5)"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    [ -n  "$1" ] && cd "$1"

    for f in 10incoming/*.csv; do

        base="${f##*/}"
        name="${base%.*}"
        ext="${base##*.}"

        bcode="${name%%-*}"
        class="${name#*-}" # B-code
        class="${class%-*}" # HHMMSS
        class="${class%-*}" # YYYYMMDD

        tabmap="legacy/$class-$bcode.tab"
        if [ ! -f "$tabmap" ]; then
            tabmap="legacy/$class.tab"
            if [ ! -f "$tabmap" ]; then
                tabmap=
            fi
        fi

        if [ -n "$tabmap" ]; then
            cat "$f" | (
                head -1 | sed -e 's/[\'"]//g' -e 's/[,:]/\n/g' (
                    xxx
                )
                cat
            ) >"11chtab/$base"

        else
        fi

    done
}

boot "$@"
