#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1769 2010-09-21 07:32:29Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Convert existing module to SDU"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] PACKAGE-NAME"
    echo
    echo "Options: "
    echo "    -q, --quiet             repeat to get less info"
    echo "    -v, --verbose           repeat to get more info"
    echo "    -h, --help              show this help page"
    echo "        --version           print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    if [ "$#" = 0 ]; then
        echo "PACKAGE-NAME isn't specified. "
        exit 1
    fi

    name=$1
    name=${name%/}
    shift

    if [ ! -d $name ]; then
        sdu-create $name "$@"
    else
        tmpdir=$name.$$.$RANDOM
        mkdir $tmpdir

        mv $name/* $tmpdir/
        sdu-create $name "$@"

        mv $tmpdir/* $name/
        rmdir $tmpdir
    fi
}

boot "$@"
