#!/bin/bash

if [ "$#" = 0 ]; then
    perlpath=(`perl -V | grep -A100 @INC | grep -v @INC`)
else
    perlpath=("$@")
fi

while read -p "Enter the package name: " pkgname; do

    resf="${pkgname//:://}.pm"
    for libdir in "${perlpath[@]}"; do
        full="$libdir/$resf"
        if [ -f "$full" ]; then
            echo "$full"
        fi
    done

done

echo
