#!/bin/bash
    . shlib-import cliboot

    RCSID='$Id: bash.sh 1853 2010-09-29 01:35:59Z lenik $'
    short_opts="hqv"
    long_opts="help,quiet,verbose,version"

function version() {
    parse_id "$RCSID"
    echo "[$BASENAME] Generate a alias-graph from BIND .db file"
    echo "Written by Lenik, Version 0.$rcs_rev, Last updated at $rcs_date"
}

function help() {
    version
    echo
    echo "Syntax: "
    echo "    $0 [OPTION] [--] ..."
    echo
    echo "Options: "
    echo "    -q, --quiet             Repeat to get less info"
    echo "    -v, --verbose           Repeat to get more info"
    echo "    -h, --help              Show this help page"
    echo "        --version           Print the version info"
}

function setopt() {
    case "$1" in
        -h|--help)
            help; exit;;
        -q|--quiet)
            LOGLEVEL=$((LOGLEVEL - 1));;
        -v|--verbose)
            LOGLEVEL=$((LOGLEVEL + 1));;
        --version)
            version; exit;;
        *)
            quit "invalid option: $1";;
    esac
}

function main() {
    echo "digraph {"
    echo '    rankdir = "RL"; '
    echo '    bb = "0, 0, 100, 600"; '
    echo "    node [ shape = box3d ]; "

    while read name rt parent comment; do
        if [ -z "${rt//[0-9]}" ]; then
            rt="$parent"
            if [ "${comment/;}" = "$comment" ]; then
                read parent comment < <(echo "$comment")
            else
                parent="$comment"
                comment=
            fi
        fi

        id="_${name//[^a-zA-Z0-9]/_}"
        parent_id="_${parent//[^a-zA-Z0-9]/_}"
        comment="${comment#;}"
        comment="${comment# }"
        label="$name";
        if [ -n "$comment" ]; then
            label="$label\n$comment"
        fi

        case "$rt" in
        A)
            echo "    $id [ label = \"$label\" ]; "
            ;;

        CNAME)
            echo "    $id [ label = \"$label\" ]; "
            echo "    $id -> $parent_id; "
            ;;
        esac

    done

    echo '}'
}

boot "$@"
