#!/bin/bash

# autokey instance|volume <id>
function autokey() {
    local class=$1
    local region=$2
    local id=$3
    local key

    key=`ifrsubst $id`
    if [ -n "$key" ]; then
        key=${key%%[*}
    else
        namevar=Name_${id//-/_}
        nametag="${!namevar}"
        if [ -n "$nametag" ]; then
            key=$class:$nametag
        else
            key=$class:$id
        fi
    fi
    echo "$key"
}

SUBST="subst -q -g"
export NO_SUBST=1

for region in us-east-1 ap-southeast-1; do

  echo "[Region $region] Query tags"

    while read type obj_type id tag_name tag_data; do
        if [ -z "$id" ]; then continue; fi
        namevar=${tag_name}_${id//-/_}
        _log2 "$namevar=\"$tag_data\""
        eval "$namevar=\"$tag_data\""
    done < <(NO_SUBST=1 ec2-describe-tags --region $region)

  echo "[Region $region] Update instances"

    ec2-describe-instances --region $region --show-empty-fields |
    while read type id ami wan lan state sec _1 _2 m1 t0 loc aki ari _3 mon ipw ipl _4 _5 st _6 _7; do
        if [ "$type" != "INSTANCE" ]; then continue; fi
        if [ "$state" != "running" ]; then continue; fi

        key=`autokey inst $region $id`
        echo "$key ($ipw)"

        $SUBST $key[id]   $id
        $SUBST $key[.rg]  $region
        $SUBST $key[.ami] $ami
        $SUBST $key[.aki] $aki
        $SUBST $key[.ari] $ari
        $SUBST $key[.loc] $loc
        $SUBST $key[wan]  $wan
        $SUBST $key[lan]  $lan
        $SUBST $key[ipw]  $ipw
        $SUBST $key[ipl]  $ipl
    done &

  echo "[Region $region] Update volumes"

    ec2-describe-volumes --region $region --show-empty-fields |
    while read type id _1 _2 loc state t0; do
        if [ "$type" != VOLUME ]; then continue; fi

        key=`autokey vol $region $id`
        echo "$key"

        $SUBST $key[id]   $id
        $SUBST $key[.rg]  $region
        $SUBST $key[.loc] $loc
        # $SUBST $key[.snap] $snap
    done &

  echo "[Region $region] Update snapshots"

    ec2-describe-snapshots --region $region --show-empty-fields |
    while read type id vol status t0 perc ser n1 desc; do
        if [ "$type" != SNAPSHOT ]; then continue; fi

        key=`autokey snap $region $id`
        echo "$key ($vol, $t0)"

        $SUBST $key[id]   $id
        $SUBST $key[.rg]  $region
        $SUBST $key[.vol] $vol
        $SUBST $key[ser]  $ser
        $SUBST $key[t0]   $t0
        $SUBST $key[desc] $desc
    done &

done
