#!/bin/bash
# Please source this file.

if [ -z "$1" ]; then
    echo ". cd-sems <module-name>"
    false
    return
fi

if ! semsroot=`svnrootofcwd stack/sems/trunk`; then
    echo "Not a SEMS working copy"
    false
    return
fi

function find_mod() {
    local start="$1"
    local name="$2"
    if [ -d "$start/$name" ]; then
        echo "$start/$name"
        return 0
    fi
    local prefix="$name"
    while [ -n "$prefix" ]; do
        if [ -d "$start/$prefix" ]; then
            if find_mod "$start/$prefix" "$name"; then
                return 0
            fi
        fi
        prefix="${prefix:0:${#prefix}-1}"
    done
    return 1
}

for mid in . archetype build modules/EBC modules/EBI modules/EBO modules/EBX; do
    if dir=`find_mod $semsroot/$mid "$1"`; then
        cd "$dir"
        return
    fi
done

echo "module not found: $1"
false
