#!/bin/bash

prefix="${1%/}"

read URL_ url < <(svn info | grep URL)
    host_="${url##*://}"
    full_cwd="${host_#*/}"
    svn_cwd="${full_cwd#repos/svn/}"

    while [ $# != 0 ]; do
        xxx_cwd="${svn_cwd#$prefix}"
        if [ "$xxx_cwd" = "$svn_cwd" ]; then
            exit 1
        fi
        svn_cwd="$xxx_cwd"
        shift
    done

cwd=`readlink -f .`
# echo sems_cwd=$sems_cwd
# echo cwd=$cwd

svnroot="${cwd%$svn_cwd}"
echo "$svnroot"
